### ISSUE TITLE
Cat issue

### ISSUE THREAD

**Issue by Gipson62** [thatalloguy/LomusEngine#1]
![Alt text](https://tenor.com/view/cat-catdriving-gif-22785638.gif)

**Comment by thatalloguy** [comment]
I am aware of this bug and it will be fixed in the new version with the working reactphysics3d library

this issue is because when creating the rigidbody of a new gameObject and adding it to the world of the current scene it returns the wrong pointer. I fixed this by adding a very complicated things called "S.T.F.U" which stands for:
-Send
-Terminal
-Floats
-upwards

which resolves the pointer error
